name: Build and Check linting

on:
  workflow_call:
    inputs:
      publish-artifact:
        default: false
        required: false
        type: boolean
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build setup
        run: |
          pip3 install ziglang
          cargo install cargo-zigbuild
          rustup target add x86_64-unknown-linux-musl
          rustup component add rustfmt
          rustup component add clippy
      # - name: lint check
      #   run: |
      #     cargo fmt --check
      #     cargo clippy --no-deps --all-features --release -- -Dwarnings
      - name: Build
        run: cargo zigbuild --release --target x86_64-unknown-linux-musl
      # - name: Run tests
      #   run: cargo test --verbose
      - run: touch .empty
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.publish-artifact }}
        with:
          name: build-musl
          path: |
            target/x86_64-unknown-linux-musl/release/icp-off-chain-agent
            .empty
